version: "3.8"

services:

  postgres:
    image: $REPOSITORY_URI/postgres:15.1

  mariadb:
    image: $REPOSITORY_URI/mariadb:10.10.2

  users-ms:
    image: $REPOSITORY_URI/elearning-demo/users-ms:latest
    build:
      dockerfile: 'Dockerfile-aws'

  courses-ms:
    image: $REPOSITORY_URI/elearning-demo/courses-ms:latest
    build:
      dockerfile: 'Dockerfile-aws'